### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by FelipeHolandaNovelino** [FelipeHolandaNovelino/GCMS-Felipe-Novelino#2]
@ramidedantas

- [x] Instalar Git localmente
- [ ] Criar projeto local
- [ ] Criar repositório local e realizar commits
- [ ]  Subir alterações para o repositório remoto
- [ ]  Fazer alterações no repositório da turma
